name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        CNAME: sandbox.is
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: build-using-github-actions
        BRANCH: gh-pages
        FOLDER: docs
        NODE_ENV: production
        BUILD_SCRIPT: npm install && npm run build
